<?xml version="1.0"?>
<!DOCTYPE mame [
<!ELEMENT mame (machine+)>
	<!ATTLIST mame build CDATA #IMPLIED>
	<!ATTLIST mame debug (yes|no) "no">
	<!ATTLIST mame mameconfig CDATA #REQUIRED>
	<!ELEMENT machine (description, year?, manufacturer?, biosset*, rom*, disk*, device_ref*, sample*, chip*, display*, sound?, input?, dipswitch*, configuration*, port*, adjuster*, driver?, feature*, device*, slot*, softwarelist*, ramoption*)>
		<!ATTLIST machine name CDATA #REQUIRED>
		<!ATTLIST machine sourcefile CDATA #IMPLIED>
		<!ATTLIST machine isbios (yes|no) "no">
		<!ATTLIST machine isdevice (yes|no) "no">
		<!ATTLIST machine ismechanical (yes|no) "no">
		<!ATTLIST machine runnable (yes|no) "yes">
		<!ATTLIST machine cloneof CDATA #IMPLIED>
		<!ATTLIST machine romof CDATA #IMPLIED>
		<!ATTLIST machine sampleof CDATA #IMPLIED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT manufacturer (#PCDATA)>
		<!ELEMENT biosset EMPTY>
			<!ATTLIST biosset name CDATA #REQUIRED>
			<!ATTLIST biosset description CDATA #REQUIRED>
			<!ATTLIST biosset default (yes|no) "no">
		<!ELEMENT rom EMPTY>
			<!ATTLIST rom name CDATA #REQUIRED>
			<!ATTLIST rom bios CDATA #IMPLIED>
			<!ATTLIST rom size CDATA #REQUIRED>
			<!ATTLIST rom crc CDATA #IMPLIED>
			<!ATTLIST rom sha1 CDATA #IMPLIED>
			<!ATTLIST rom merge CDATA #IMPLIED>
			<!ATTLIST rom region CDATA #IMPLIED>
			<!ATTLIST rom offset CDATA #IMPLIED>
			<!ATTLIST rom status (baddump|nodump|good) "good">
			<!ATTLIST rom optional (yes|no) "no">
		<!ELEMENT disk EMPTY>
			<!ATTLIST disk name CDATA #REQUIRED>
			<!ATTLIST disk sha1 CDATA #IMPLIED>
			<!ATTLIST disk merge CDATA #IMPLIED>
			<!ATTLIST disk region CDATA #IMPLIED>
			<!ATTLIST disk index CDATA #IMPLIED>
			<!ATTLIST disk writable (yes|no) "no">
			<!ATTLIST disk status (baddump|nodump|good) "good">
			<!ATTLIST disk optional (yes|no) "no">
		<!ELEMENT device_ref EMPTY>
			<!ATTLIST device_ref name CDATA #REQUIRED>
		<!ELEMENT sample EMPTY>
			<!ATTLIST sample name CDATA #REQUIRED>
		<!ELEMENT chip EMPTY>
			<!ATTLIST chip name CDATA #REQUIRED>
			<!ATTLIST chip tag CDATA #IMPLIED>
			<!ATTLIST chip type (cpu|audio) #REQUIRED>
			<!ATTLIST chip clock CDATA #IMPLIED>
		<!ELEMENT display EMPTY>
			<!ATTLIST display tag CDATA #IMPLIED>
			<!ATTLIST display type (raster|vector|lcd|svg|unknown) #REQUIRED>
			<!ATTLIST display rotate (0|90|180|270) #IMPLIED>
			<!ATTLIST display flipx (yes|no) "no">
			<!ATTLIST display width CDATA #IMPLIED>
			<!ATTLIST display height CDATA #IMPLIED>
			<!ATTLIST display refresh CDATA #REQUIRED>
			<!ATTLIST display pixclock CDATA #IMPLIED>
			<!ATTLIST display htotal CDATA #IMPLIED>
			<!ATTLIST display hbend CDATA #IMPLIED>
			<!ATTLIST display hbstart CDATA #IMPLIED>
			<!ATTLIST display vtotal CDATA #IMPLIED>
			<!ATTLIST display vbend CDATA #IMPLIED>
			<!ATTLIST display vbstart CDATA #IMPLIED>
		<!ELEMENT sound EMPTY>
			<!ATTLIST sound channels CDATA #REQUIRED>
		<!ELEMENT condition EMPTY>
			<!ATTLIST condition tag CDATA #REQUIRED>
			<!ATTLIST condition mask CDATA #REQUIRED>
			<!ATTLIST condition relation (eq|ne|gt|le|lt|ge) #REQUIRED>
			<!ATTLIST condition value CDATA #REQUIRED>
		<!ELEMENT input (control*)>
			<!ATTLIST input service (yes|no) "no">
			<!ATTLIST input tilt (yes|no) "no">
			<!ATTLIST input players CDATA #REQUIRED>
			<!ATTLIST input coins CDATA #IMPLIED>
			<!ELEMENT control EMPTY>
				<!ATTLIST control type CDATA #REQUIRED>
				<!ATTLIST control player CDATA #IMPLIED>
				<!ATTLIST control buttons CDATA #IMPLIED>
				<!ATTLIST control reqbuttons CDATA #IMPLIED>
				<!ATTLIST control minimum CDATA #IMPLIED>
				<!ATTLIST control maximum CDATA #IMPLIED>
				<!ATTLIST control sensitivity CDATA #IMPLIED>
				<!ATTLIST control keydelta CDATA #IMPLIED>
				<!ATTLIST control reverse (yes|no) "no">
				<!ATTLIST control ways CDATA #IMPLIED>
				<!ATTLIST control ways2 CDATA #IMPLIED>
				<!ATTLIST control ways3 CDATA #IMPLIED>
		<!ELEMENT dipswitch (condition?, diplocation*, dipvalue*)>
			<!ATTLIST dipswitch name CDATA #REQUIRED>
			<!ATTLIST dipswitch tag CDATA #REQUIRED>
			<!ATTLIST dipswitch mask CDATA #REQUIRED>
			<!ELEMENT diplocation EMPTY>
				<!ATTLIST diplocation name CDATA #REQUIRED>
				<!ATTLIST diplocation number CDATA #REQUIRED>
				<!ATTLIST diplocation inverted (yes|no) "no">
			<!ELEMENT dipvalue (condition?)>
				<!ATTLIST dipvalue name CDATA #REQUIRED>
				<!ATTLIST dipvalue value CDATA #REQUIRED>
				<!ATTLIST dipvalue default (yes|no) "no">
		<!ELEMENT configuration (condition?, conflocation*, confsetting*)>
			<!ATTLIST configuration name CDATA #REQUIRED>
			<!ATTLIST configuration tag CDATA #REQUIRED>
			<!ATTLIST configuration mask CDATA #REQUIRED>
			<!ELEMENT conflocation EMPTY>
				<!ATTLIST conflocation name CDATA #REQUIRED>
				<!ATTLIST conflocation number CDATA #REQUIRED>
				<!ATTLIST conflocation inverted (yes|no) "no">
			<!ELEMENT confsetting (condition?)>
				<!ATTLIST confsetting name CDATA #REQUIRED>
				<!ATTLIST confsetting value CDATA #REQUIRED>
				<!ATTLIST confsetting default (yes|no) "no">
		<!ELEMENT port (analog*)>
			<!ATTLIST port tag CDATA #REQUIRED>
			<!ELEMENT analog EMPTY>
				<!ATTLIST analog mask CDATA #REQUIRED>
		<!ELEMENT adjuster (condition?)>
			<!ATTLIST adjuster name CDATA #REQUIRED>
			<!ATTLIST adjuster default CDATA #REQUIRED>
		<!ELEMENT driver EMPTY>
			<!ATTLIST driver status (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver emulation (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver cocktail (good|imperfect|preliminary) #IMPLIED>
			<!ATTLIST driver savestate (supported|unsupported) #REQUIRED>
			<!ATTLIST driver requiresartwork (yes|no) "no">
			<!ATTLIST driver unofficial (yes|no) "no">
			<!ATTLIST driver nosoundhardware (yes|no) "no">
			<!ATTLIST driver incomplete (yes|no) "no">
		<!ELEMENT feature EMPTY>
			<!ATTLIST feature type (protection|timing|graphics|palette|sound|capture|camera|microphone|controls|keyboard|mouse|media|disk|printer|tape|punch|drum|rom|comms|lan|wan) #REQUIRED>
			<!ATTLIST feature status (unemulated|imperfect) #IMPLIED>
			<!ATTLIST feature overall (unemulated|imperfect) #IMPLIED>
		<!ELEMENT device (instance?, extension*)>
			<!ATTLIST device type CDATA #REQUIRED>
			<!ATTLIST device tag CDATA #IMPLIED>
			<!ATTLIST device fixed_image CDATA #IMPLIED>
			<!ATTLIST device mandatory CDATA #IMPLIED>
			<!ATTLIST device interface CDATA #IMPLIED>
			<!ELEMENT instance EMPTY>
				<!ATTLIST instance name CDATA #REQUIRED>
				<!ATTLIST instance briefname CDATA #REQUIRED>
			<!ELEMENT extension EMPTY>
				<!ATTLIST extension name CDATA #REQUIRED>
		<!ELEMENT slot (slotoption*)>
			<!ATTLIST slot name CDATA #REQUIRED>
			<!ELEMENT slotoption EMPTY>
				<!ATTLIST slotoption name CDATA #REQUIRED>
				<!ATTLIST slotoption devname CDATA #REQUIRED>
				<!ATTLIST slotoption default (yes|no) "no">
		<!ELEMENT softwarelist EMPTY>
			<!ATTLIST softwarelist tag CDATA #REQUIRED>
			<!ATTLIST softwarelist name CDATA #REQUIRED>
			<!ATTLIST softwarelist status (original|compatible) #REQUIRED>
			<!ATTLIST softwarelist filter CDATA #IMPLIED>
		<!ELEMENT ramoption (#PCDATA)>
			<!ATTLIST ramoption name CDATA #REQUIRED>
			<!ATTLIST ramoption default CDATA #IMPLIED>
]>

<mame build="0.235 (mame0235)" debug="no" mameconfig="10">
	<machine name="18wheelr" sourcefile="naomi.cpp" romof="naomi">
		<description>18 Wheeler (deluxe, Rev A)</description>
		<year>2000</year>
		<manufacturer>Sega</manufacturer>
		<biosset name="bios0" description="epr-21576h (Japan)"/>
		<biosset name="bios1" description="epr-21576g (Japan)"/>
		<biosset name="bios2" description="epr-21576e (Japan)"/>
		<biosset name="bios3" description="epr-21576d (Japan)"/>
		<biosset name="bios4" description="epr-21576c (Japan)"/>
		<biosset name="bios5" description="epr-21576b (Japan)"/>
		<biosset name="bios6" description="epr-21576a (Japan)"/>
		<biosset name="bios7" description="epr-21576 (Japan)"/>
		<biosset name="bios8" description="epr-21578h (Export)"/>
		<biosset name="bios9" description="epr-21578g (Export)"/>
		<biosset name="bios10" description="epr-21578f (Export)"/>
		<biosset name="bios11" description="epr-21578e (Export)"/>
		<biosset name="bios12" description="epr-21578d (Export)"/>
		<biosset name="bios13" description="epr-21578a (Export)"/>
		<biosset name="bios14" description="epr-21577h (USA)"/>
		<biosset name="bios15" description="epr-21577g (USA)"/>
		<biosset name="bios16" description="epr-21577e (USA)"/>
		<biosset name="bios17" description="epr-21577d (USA)"/>
		<biosset name="bios18" description="epr-21577a (USA)"/>
		<biosset name="bios19" description="epr-21579d (Korea)"/>
		<biosset name="bios20" description="epr-21579 (Korea)"/>
		<biosset name="bios21" description="Set4 Dev BIOS"/>
		<biosset name="bios22" description="Dev BIOS v1.10"/>
		<biosset name="bios23" description="Dev BIOS (Nov 1998)"/>
		<biosset name="bios24" description="Development ROM Board"/>
		<biosset name="bios25" description="epr-21576h (multi-region hack)"/>
		<rom name="epr-21576h.ic27" merge="epr-21576h.ic27" bios="bios0" size="2097152" crc="d4895685" sha1="91424d481ff99a8d3f4c45cea6d3f0eada049a6d" region="maincpu" offset="0"/>
		<rom name="epr-21576g.ic27" merge="epr-21576g.ic27" bios="bios1" size="2097152" crc="d2a1c6bf" sha1="6d27d71aec4dfba98f66316ae74a1426d567698a" region="maincpu" offset="0"/>
		<rom name="epr-21576e.ic27" merge="epr-21576e.ic27" bios="bios2" size="2097152" crc="08c0add7" sha1="e7c1a7673cb2ccb21748ef44105e46d1bad7266d" region="maincpu" offset="0"/>
		<rom name="epr-21576d.ic27" merge="epr-21576d.ic27" bios="bios3" size="2097152" crc="3b2afa7b" sha1="d007e1d321c198a38c5baff86eb2ab84385d150a" region="maincpu" offset="0"/>
		<rom name="epr-21576c.ic27" merge="epr-21576c.ic27" bios="bios4" size="2097152" crc="4599ad13" sha1="7e730e9452a792d76f210c33a955d385538682c7" status="baddump" region="maincpu" offset="0"/>
		<rom name="epr-21576b.ic27" merge="epr-21576b.ic27" bios="bios5" size="2097152" crc="755a6e07" sha1="7e8b8ccfc063144d89668e7224dcd8a36c54f3b3" region="maincpu" offset="0"/>
		<rom name="epr-21576a.ic27" merge="epr-21576a.ic27" bios="bios6" size="2097152" crc="cedfe439" sha1="f27798bf3d890863ef0c1d9dcb4e7782249dca27" region="maincpu" offset="0"/>
		<rom name="epr-21576.ic27" merge="epr-21576.ic27" bios="bios7" size="2097152" crc="9dad3495" sha1="5fb66f9a2b68d120f059c72758e65d34f461044a" region="maincpu" offset="0"/>
		<rom name="epr-21578h.ic27" merge="epr-21578h.ic27" bios="bios8" size="2097152" crc="7b452946" sha1="8e9f153bbada24b37066dc45b64a7bf0d4f26a9b" region="maincpu" offset="0"/>
		<rom name="epr-21578g.ic27" merge="epr-21578g.ic27" bios="bios9" size="2097152" crc="55413214" sha1="bd2748365a9fc1821c9369aa7155d7c41c4df43e" region="maincpu" offset="0"/>
		<rom name="epr-21578f.ic27" merge="epr-21578f.ic27" bios="bios10" size="2097152" crc="628a27fd" sha1="dae7add616b1a2478f00608823e88c3b82a0e78f" region="maincpu" offset="0"/>
		<rom name="epr-21578e.ic27" merge="epr-21578e.ic27" bios="bios11" size="2097152" crc="087f09a3" sha1="0418eb2cf9766f0b1b874a4e92528779e22c0a4a" region="maincpu" offset="0"/>
		<rom name="epr-21578d.ic27" merge="epr-21578d.ic27" bios="bios12" size="2097152" crc="dfd5f42a" sha1="614a0db4743a5e5a206190d6786ade24325afbfd" region="maincpu" offset="0"/>
		<rom name="epr-21578a.ic27" merge="epr-21578a.ic27" bios="bios13" size="2097152" crc="6c9aad83" sha1="555918de76d8dbee2a97d8a95297ef694b3e803f" region="maincpu" offset="0"/>
		<rom name="epr-21577h.ic27" merge="epr-21577h.ic27" bios="bios14" size="2097152" crc="fdf17452" sha1="5f3e4b677f0046ce690a4f096b0481e5dd8bb6e6" region="maincpu" offset="0"/>
		<rom name="epr-21577g.ic27" merge="epr-21577g.ic27" bios="bios15" size="2097152" crc="25f64af7" sha1="99f9e6cc0642319bd2da492611220540add573e8" region="maincpu" offset="0"/>
		<rom name="epr-21577e.ic27" merge="epr-21577e.ic27" bios="bios16" size="2097152" crc="cf36e97b" sha1="b085305982e7572e58b03a9d35f17ae319c3bbc6" region="maincpu" offset="0"/>
		<rom name="epr-21577d.ic27" merge="epr-21577d.ic27" bios="bios17" size="2097152" crc="60ddcbbe" sha1="58b15096d269d6df617ca1810b66b47deb184958" region="maincpu" offset="0"/>
		<rom name="epr-21577a.ic27" merge="epr-21577a.ic27" bios="bios18" size="2097152" crc="969dc491" sha1="581d1eae328b87b67508a7586ffc60cee256f70f" region="maincpu" offset="0"/>
		<rom name="epr-21579d.ic27" merge="epr-21579d.ic27" bios="bios19" size="2097152" crc="33513691" sha1="b1d8c7c516e1471a788fcf7a02a794ad2f05aeeb" region="maincpu" offset="0"/>
		<rom name="epr-21579.ic27" merge="epr-21579.ic27" bios="bios20" size="2097152" crc="71f9c918" sha1="d15af8b947f41eea7c203b565cd403e3f37a2017" region="maincpu" offset="0"/>
		<rom name="boot_rom_64b8.ic606" merge="boot_rom_64b8.ic606" bios="bios21" size="524288" crc="7a50fab9" sha1="ef79f448e0bf735d1264ad4f051d24178822110f" region="maincpu" offset="0"/>
		<rom name="develop110.ic27" merge="develop110.ic27" bios="bios22" size="2097152" crc="de7cfdb0" sha1="da16800edc4d49f70481c124d487f544c2fa8ce7" region="maincpu" offset="0"/>
		<rom name="develop.ic27" merge="develop.ic27" bios="bios23" size="2097152" crc="309a196a" sha1="409b50371feb648f10efd6b7ac420bf08d9a3b5a" region="maincpu" offset="0"/>
		<rom name="zukinver0930.ic25" merge="zukinver0930.ic25" bios="bios24" size="2097152" crc="58e17c23" sha1="19330f906accf1b859f56bbcedc2edff73747599" region="maincpu" offset="0"/>
		<rom name="epr-21576h_multi.ic27" merge="epr-21576h_multi.ic27" bios="bios25" size="2097152" crc="cce01f1f" sha1="cca17119ad13e3a4ef7cb6902a37b65d6a844aee" region="maincpu" offset="0"/>
		<rom name="315-6188.ic31" merge="315-6188.ic31" size="8244" crc="7c9fea46" sha1="f77c07ae65dfed18c1c4c632c8945be21d02ddaf" region="altera_pof" offset="0"/>
		<rom name="main_eeprom.bin" merge="main_eeprom.bin" size="128" crc="fea29cbb" sha1="4099f1747aafa07db34f6e072cd9bfaa83bae10e" region="main_eeprom" offset="0"/>
		<rom name="x76f100_eeprom.bin" merge="x76f100_eeprom.bin" size="132" crc="3ea24b6a" sha1="3a730ebcf56e0060fef6b1b02eb2eb7cfb7e61dc" region="naomibd_eeprom" offset="0"/>
		<rom name="epr-22185a.ic22" size="4194304" crc="219b29b0" sha1="2f32caf3906fc1408fd8126a500e74c682ff20fa" region="rom_board" offset="0"/>
		<rom name="mpr-22164.ic1" size="8388608" crc="ca045315" sha1="0c5becb5220659fa86f1e7901032f8c9a1329a51" region="rom_board" offset="800000"/>
		<rom name="mpr-22165.ic2" size="8388608" crc="e43f4ba8" sha1="768159bccae6a72c809e9f374538df304c92fbfe" region="rom_board" offset="1000000"/>
		<rom name="mpr-22166.ic3" size="8388608" crc="ea67edb1" sha1="1214fdbfd8ce9f7a2b33e97f7c4e22ebb3eee988" region="rom_board" offset="1800000"/>
		<rom name="mpr-22167.ic4" size="8388608" crc="df6125e2" sha1="7244278cf89b88dbc7b8b1e3a537bf0b3f521c3a" region="rom_board" offset="2000000"/>
		<rom name="mpr-22168.ic5" size="8388608" crc="8a919f9c" sha1="28f1f9d8943e0a0b7bc186808cdab5d21d914e05" region="rom_board" offset="2800000"/>
		<rom name="mpr-22169.ic6" size="8388608" crc="a0fa7d68" sha1="010fc87f0df3cf9e3d01a5ca4d4aa7e84728652d" region="rom_board" offset="3000000"/>
		<rom name="mpr-22170.ic7" size="8388608" crc="1f407049" sha1="3c11b25168715d200f8d78a3db7bfc8cb3c29897" region="rom_board" offset="3800000"/>
		<rom name="mpr-22171.ic8" size="8388608" crc="03ce8dcd" sha1="9bf1eb0a2628317bea5d8899e34f6f4363729c52" region="rom_board" offset="4000000"/>
		<rom name="mpr-22172.ic9" size="8388608" crc="c3e8c978" sha1="96cbaa0f13e22365b04818cb5cad2ddc2027e38a" region="rom_board" offset="4800000"/>
		<rom name="mpr-22173.ic10" size="8388608" crc="3caec8fc" sha1="88ee6b0a1735788570d0a6507eec14a31ebabb9a" region="rom_board" offset="5000000"/>
		<rom name="mpr-22174.ic11" size="8388608" crc="17245a27" sha1="b3701155b1bbdbcbfb5ea686470c3c432d2573b7" region="rom_board" offset="5800000"/>
		<rom name="mpr-22175.ic12s" size="8388608" crc="4d984682" sha1="60270d6caa3bbc0025a0c01cf4d7b10783216e0b" region="rom_board" offset="6000000"/>
		<rom name="mpr-22176.ic13s" size="8388608" crc="3ea2403f" sha1="efde74c621a8fe17d8aa3a24da35e2ca6bc0bd9a" region="rom_board" offset="6800000"/>
		<rom name="mpr-22177.ic14s" size="8388608" crc="15514cbc" sha1="0171d67560b8d72ca3f718dcce301acc60dee1fa" region="rom_board" offset="7000000"/>
		<rom name="mpr-22178.ic15s" size="8388608" crc="9ea0552f" sha1="4b282110ef9f60f942518f3849acfff4a5faf4bd" region="rom_board" offset="7800000"/>
		<rom name="mpr-22179.ic16s" size="8388608" crc="6915c4e6" sha1="b44d49edcfdc0f2958bf1a3856b09b5442e8f1a3" region="rom_board" offset="8000000"/>
		<rom name="mpr-22180.ic17s" size="8388608" crc="744c3a40" sha1="56fba6ebc45d542ba6e4f4dd205194344f127ac2" region="rom_board" offset="8800000"/>
		<rom name="mpr-22181.ic18s" size="8388608" crc="5a39b68e" sha1="0f81ed1116b1829262f320fc82f93df107b6f848" region="rom_board" offset="9000000"/>
		<rom name="mpr-22182.ic19s" size="8388608" crc="c5606c42" sha1="5871104ff1c7acde0493e13b9a4d0abdf8a40728" region="rom_board" offset="9800000"/>
		<rom name="mpr-22183.ic20s" size="8388608" crc="776af308" sha1="7d29cb4dce75d34c622549fea7e102868d0da60a" region="rom_board" offset="a000000"/>
		<rom name="epr-21868.ic7" size="65536" crc="c306a51f" sha1="7833b73dc34c4c62401a30637968f46b949ceac0" region="jvsio" offset="0"/>
		<rom name="epr-21868p.ic7" size="65536" crc="5d7b75f0" sha1="faf7f06636b70298eb15770da4b0f7c435755dcb" region="jvsio" offset="0"/>
		<rom name="epr-22082.ic7" size="65536" crc="de26fc6c" sha1="cf8ef7969770fff8697299c3e3152413b898a967" region="jvsio" offset="10000"/>
		<rom name="epr-24354.ic7" size="65536" crc="0ce43505" sha1="7700e3acfb756dfbf95f3ff14786d1bcb57e2f7d" region="jvsio" offset="0"/>
		<rom name="epr-23000.ic8" size="65536" crc="e3b162f7" sha1="52c7ad759c3c4a3148764e14d77ba5006bc8af48" region="motorio" offset="0"/>
		<device_ref name="sh4le"/>
		<device_ref name="timer"/>
		<device_ref name="arm7_le"/>
		<device_ref name="maple_dc"/>
		<device_ref name="screen"/>
		<device_ref name="palette"/>
		<device_ref name="powervr2"/>
		<device_ref name="speaker"/>
		<device_ref name="speaker"/>
		<device_ref name="aica"/>
		<device_ref name="aicartc"/>
		<device_ref name="93c46_16"/>
		<device_ref name="mie"/>
		<device_ref name="z80"/>
		<device_ref name="mie_jvs"/>
		<device_ref name="jvs13551"/>
		<device_ref name="tmp90ph44"/>
		<device_ref name="93c46_8"/>
		<device_ref name="x76f100"/>
		<device_ref name="m3comm"/>
		<device_ref name="m68000"/>
		<device_ref name="ram"/>
		<device_ref name="nvram"/>
		<device_ref name="naomi_m2_board"/>
		<device_ref name="sega315_5881"/>
		<chip type="cpu" tag="maincpu" name="Hitachi SH-4 (little)" clock="200000000"/>
		<chip type="cpu" tag="soundcpu" name="ARM7 (little)" clock="2822400"/>
		<chip type="cpu" tag="mie_maple:mie" name="Zilog Z80" clock="16000000"/>
		<chip type="cpu" tag="837_13551:iomcu" name="Toshiba TMP90PH44" clock="10000000"/>
		<chip type="cpu" tag="comm_board:m3commcpu" name="Motorola MC68000" clock="10000000"/>
		<chip type="audio" tag="lspeaker" name="Speaker"/>
		<chip type="audio" tag="rspeaker" name="Speaker"/>
		<chip type="audio" tag="aica" name="Yamaha AICA" clock="22579200"/>
		<display tag="screen" type="raster" rotate="0" width="640" height="480" refresh="61.702586" pixclock="26917136" htotal="820" hbend="0" hbstart="640" vtotal="532" vbend="0" vbstart="480" />
		<sound channels="2"/>
		<input players="1" coins="2" service="yes" tilt="yes">
			<control type="paddle" buttons="5" minimum="0" maximum="65280" sensitivity="30" keydelta="30"/>
			<control type="pedal" minimum="0" maximum="65280" sensitivity="100" keydelta="40"/>
		</input>
		<dipswitch name="Monitor" tag="MIE.5" mask="1">
			<diplocation name="SW1" number="1"/>
			<dipvalue name="31 kHz" value="1"/>
			<dipvalue name="15 kHz" value="0" default="yes"/>
		</dipswitch>
		<dipswitch name="Unknown" tag="MIE.5" mask="2">
			<diplocation name="SW1" number="2"/>
			<dipvalue name="Off" value="2" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Unknown" tag="MIE.5" mask="4">
			<diplocation name="SW1" number="3"/>
			<dipvalue name="Off" value="4" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Unknown" tag="MIE.5" mask="8">
			<diplocation name="SW1" number="4"/>
			<dipvalue name="Off" value="8" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<configuration name="Bilinear Filtering" tag="MAMEDEBUG" mask="1">
			<confsetting name="No" value="0" default="yes"/>
			<confsetting name="Yes" value="1"/>
		</configuration>
		<configuration name="Disable Render Calls" tag="MAMEDEBUG" mask="2">
			<confsetting name="No" value="0" default="yes"/>
			<confsetting name="Yes" value="2"/>
		</configuration>
		<port tag=":837_13551:COINS">
		</port>
		<port tag=":A0">
			<analog mask="65280"/>
		</port>
		<port tag=":A1">
			<analog mask="65280"/>
		</port>
		<port tag=":A2">
			<analog mask="65280"/>
		</port>
		<port tag=":MAMEDEBUG">
		</port>
		<port tag=":MIE.3">
		</port>
		<port tag=":MIE.5">
		</port>
		<port tag=":P1">
		</port>
		<port tag=":P2">
		</port>
		<port tag=":TILT">
		</port>
		<driver status="preliminary" emulation="preliminary" savestate="unsupported"/>
		<feature type="graphics" status="imperfect"/>
		<feature type="sound" status="imperfect"/>
	</machine>
	<machine name="18wheelro" sourcefile="naomi.cpp" cloneof="18wheelr" romof="18wheelr">
		<description>18 Wheeler (deluxe)</description>
		<year>2000</year>
		<manufacturer>Sega</manufacturer>
		<biosset name="bios0" description="epr-21576h (Japan)"/>
		<biosset name="bios1" description="epr-21576g (Japan)"/>
		<biosset name="bios2" description="epr-21576e (Japan)"/>
		<biosset name="bios3" description="epr-21576d (Japan)"/>
		<biosset name="bios4" description="epr-21576c (Japan)"/>
		<biosset name="bios5" description="epr-21576b (Japan)"/>
		<biosset name="bios6" description="epr-21576a (Japan)"/>
		<biosset name="bios7" description="epr-21576 (Japan)"/>
		<biosset name="bios8" description="epr-21578h (Export)"/>
		<biosset name="bios9" description="epr-21578g (Export)"/>
		<biosset name="bios10" description="epr-21578f (Export)"/>
		<biosset name="bios11" description="epr-21578e (Export)"/>
		<biosset name="bios12" description="epr-21578d (Export)"/>
		<biosset name="bios13" description="epr-21578a (Export)"/>
		<biosset name="bios14" description="epr-21577h (USA)"/>
		<biosset name="bios15" description="epr-21577g (USA)"/>
		<biosset name="bios16" description="epr-21577e (USA)"/>
		<biosset name="bios17" description="epr-21577d (USA)"/>
		<biosset name="bios18" description="epr-21577a (USA)"/>
		<biosset name="bios19" description="epr-21579d (Korea)"/>
		<biosset name="bios20" description="epr-21579 (Korea)"/>
		<biosset name="bios21" description="Set4 Dev BIOS"/>
		<biosset name="bios22" description="Dev BIOS v1.10"/>
		<biosset name="bios23" description="Dev BIOS (Nov 1998)"/>
		<biosset name="bios24" description="Development ROM Board"/>
		<biosset name="bios25" description="epr-21576h (multi-region hack)"/>
		<rom name="epr-21576h.ic27" merge="epr-21576h.ic27" bios="bios0" size="2097152" crc="d4895685" sha1="91424d481ff99a8d3f4c45cea6d3f0eada049a6d" region="maincpu" offset="0"/>
		<rom name="epr-21576g.ic27" merge="epr-21576g.ic27" bios="bios1" size="2097152" crc="d2a1c6bf" sha1="6d27d71aec4dfba98f66316ae74a1426d567698a" region="maincpu" offset="0"/>
		<rom name="epr-21576e.ic27" merge="epr-21576e.ic27" bios="bios2" size="2097152" crc="08c0add7" sha1="e7c1a7673cb2ccb21748ef44105e46d1bad7266d" region="maincpu" offset="0"/>
		<rom name="epr-21576d.ic27" merge="epr-21576d.ic27" bios="bios3" size="2097152" crc="3b2afa7b" sha1="d007e1d321c198a38c5baff86eb2ab84385d150a" region="maincpu" offset="0"/>
		<rom name="epr-21576c.ic27" merge="epr-21576c.ic27" bios="bios4" size="2097152" crc="4599ad13" sha1="7e730e9452a792d76f210c33a955d385538682c7" status="baddump" region="maincpu" offset="0"/>
		<rom name="epr-21576b.ic27" merge="epr-21576b.ic27" bios="bios5" size="2097152" crc="755a6e07" sha1="7e8b8ccfc063144d89668e7224dcd8a36c54f3b3" region="maincpu" offset="0"/>
		<rom name="epr-21576a.ic27" merge="epr-21576a.ic27" bios="bios6" size="2097152" crc="cedfe439" sha1="f27798bf3d890863ef0c1d9dcb4e7782249dca27" region="maincpu" offset="0"/>
		<rom name="epr-21576.ic27" merge="epr-21576.ic27" bios="bios7" size="2097152" crc="9dad3495" sha1="5fb66f9a2b68d120f059c72758e65d34f461044a" region="maincpu" offset="0"/>
		<rom name="epr-21578h.ic27" merge="epr-21578h.ic27" bios="bios8" size="2097152" crc="7b452946" sha1="8e9f153bbada24b37066dc45b64a7bf0d4f26a9b" region="maincpu" offset="0"/>
		<rom name="epr-21578g.ic27" merge="epr-21578g.ic27" bios="bios9" size="2097152" crc="55413214" sha1="bd2748365a9fc1821c9369aa7155d7c41c4df43e" region="maincpu" offset="0"/>
		<rom name="epr-21578f.ic27" merge="epr-21578f.ic27" bios="bios10" size="2097152" crc="628a27fd" sha1="dae7add616b1a2478f00608823e88c3b82a0e78f" region="maincpu" offset="0"/>
		<rom name="epr-21578e.ic27" merge="epr-21578e.ic27" bios="bios11" size="2097152" crc="087f09a3" sha1="0418eb2cf9766f0b1b874a4e92528779e22c0a4a" region="maincpu" offset="0"/>
		<rom name="epr-21578d.ic27" merge="epr-21578d.ic27" bios="bios12" size="2097152" crc="dfd5f42a" sha1="614a0db4743a5e5a206190d6786ade24325afbfd" region="maincpu" offset="0"/>
		<rom name="epr-21578a.ic27" merge="epr-21578a.ic27" bios="bios13" size="2097152" crc="6c9aad83" sha1="555918de76d8dbee2a97d8a95297ef694b3e803f" region="maincpu" offset="0"/>
		<rom name="epr-21577h.ic27" merge="epr-21577h.ic27" bios="bios14" size="2097152" crc="fdf17452" sha1="5f3e4b677f0046ce690a4f096b0481e5dd8bb6e6" region="maincpu" offset="0"/>
		<rom name="epr-21577g.ic27" merge="epr-21577g.ic27" bios="bios15" size="2097152" crc="25f64af7" sha1="99f9e6cc0642319bd2da492611220540add573e8" region="maincpu" offset="0"/>
		<rom name="epr-21577e.ic27" merge="epr-21577e.ic27" bios="bios16" size="2097152" crc="cf36e97b" sha1="b085305982e7572e58b03a9d35f17ae319c3bbc6" region="maincpu" offset="0"/>
		<rom name="epr-21577d.ic27" merge="epr-21577d.ic27" bios="bios17" size="2097152" crc="60ddcbbe" sha1="58b15096d269d6df617ca1810b66b47deb184958" region="maincpu" offset="0"/>
		<rom name="epr-21577a.ic27" merge="epr-21577a.ic27" bios="bios18" size="2097152" crc="969dc491" sha1="581d1eae328b87b67508a7586ffc60cee256f70f" region="maincpu" offset="0"/>
		<rom name="epr-21579d.ic27" merge="epr-21579d.ic27" bios="bios19" size="2097152" crc="33513691" sha1="b1d8c7c516e1471a788fcf7a02a794ad2f05aeeb" region="maincpu" offset="0"/>
		<rom name="epr-21579.ic27" merge="epr-21579.ic27" bios="bios20" size="2097152" crc="71f9c918" sha1="d15af8b947f41eea7c203b565cd403e3f37a2017" region="maincpu" offset="0"/>
		<rom name="boot_rom_64b8.ic606" merge="boot_rom_64b8.ic606" bios="bios21" size="524288" crc="7a50fab9" sha1="ef79f448e0bf735d1264ad4f051d24178822110f" region="maincpu" offset="0"/>
		<rom name="develop110.ic27" merge="develop110.ic27" bios="bios22" size="2097152" crc="de7cfdb0" sha1="da16800edc4d49f70481c124d487f544c2fa8ce7" region="maincpu" offset="0"/>
		<rom name="develop.ic27" merge="develop.ic27" bios="bios23" size="2097152" crc="309a196a" sha1="409b50371feb648f10efd6b7ac420bf08d9a3b5a" region="maincpu" offset="0"/>
		<rom name="zukinver0930.ic25" merge="zukinver0930.ic25" bios="bios24" size="2097152" crc="58e17c23" sha1="19330f906accf1b859f56bbcedc2edff73747599" region="maincpu" offset="0"/>
		<rom name="epr-21576h_multi.ic27" merge="epr-21576h_multi.ic27" bios="bios25" size="2097152" crc="cce01f1f" sha1="cca17119ad13e3a4ef7cb6902a37b65d6a844aee" region="maincpu" offset="0"/>
		<rom name="315-6188.ic31" merge="315-6188.ic31" size="8244" crc="7c9fea46" sha1="f77c07ae65dfed18c1c4c632c8945be21d02ddaf" region="altera_pof" offset="0"/>
		<rom name="main_eeprom.bin" merge="main_eeprom.bin" size="128" crc="fea29cbb" sha1="4099f1747aafa07db34f6e072cd9bfaa83bae10e" region="main_eeprom" offset="0"/>
		<rom name="x76f100_eeprom.bin" merge="x76f100_eeprom.bin" size="132" crc="3ea24b6a" sha1="3a730ebcf56e0060fef6b1b02eb2eb7cfb7e61dc" region="naomibd_eeprom" offset="0"/>
		<rom name="epr-22185.ic22" size="4194304" crc="bd910478" sha1="6db3bfa23246c250e334bbd54dcb5038a2d18dbc" region="rom_board" offset="0"/>
		<rom name="mpr-22164.ic1" merge="mpr-22164.ic1" size="8388608" crc="ca045315" sha1="0c5becb5220659fa86f1e7901032f8c9a1329a51" region="rom_board" offset="800000"/>
		<rom name="mpr-22165.ic2" merge="mpr-22165.ic2" size="8388608" crc="e43f4ba8" sha1="768159bccae6a72c809e9f374538df304c92fbfe" region="rom_board" offset="1000000"/>
		<rom name="mpr-22166.ic3" merge="mpr-22166.ic3" size="8388608" crc="ea67edb1" sha1="1214fdbfd8ce9f7a2b33e97f7c4e22ebb3eee988" region="rom_board" offset="1800000"/>
		<rom name="mpr-22167.ic4" merge="mpr-22167.ic4" size="8388608" crc="df6125e2" sha1="7244278cf89b88dbc7b8b1e3a537bf0b3f521c3a" region="rom_board" offset="2000000"/>
		<rom name="mpr-22168.ic5" merge="mpr-22168.ic5" size="8388608" crc="8a919f9c" sha1="28f1f9d8943e0a0b7bc186808cdab5d21d914e05" region="rom_board" offset="2800000"/>
		<rom name="mpr-22169.ic6" merge="mpr-22169.ic6" size="8388608" crc="a0fa7d68" sha1="010fc87f0df3cf9e3d01a5ca4d4aa7e84728652d" region="rom_board" offset="3000000"/>
		<rom name="mpr-22170.ic7" merge="mpr-22170.ic7" size="8388608" crc="1f407049" sha1="3c11b25168715d200f8d78a3db7bfc8cb3c29897" region="rom_board" offset="3800000"/>
		<rom name="mpr-22171.ic8" merge="mpr-22171.ic8" size="8388608" crc="03ce8dcd" sha1="9bf1eb0a2628317bea5d8899e34f6f4363729c52" region="rom_board" offset="4000000"/>
		<rom name="mpr-22172.ic9" merge="mpr-22172.ic9" size="8388608" crc="c3e8c978" sha1="96cbaa0f13e22365b04818cb5cad2ddc2027e38a" region="rom_board" offset="4800000"/>
		<rom name="mpr-22173.ic10" merge="mpr-22173.ic10" size="8388608" crc="3caec8fc" sha1="88ee6b0a1735788570d0a6507eec14a31ebabb9a" region="rom_board" offset="5000000"/>